---
title: "Carp Network Topology"
author: "Lauren White"
date: "2/24/2020"
output: html_document
---

Script to focus on daily network properties at single sites.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(stringr)
library(lubridate)
library(Matrix)
library(igraph)
library(bipartite)
library(data.table)
library(ggplot2)
library(gganimate)
```

## Boatramp
### Load PIT Tag capture and Boatramp site-specific data

```{r}
#Capture data: refromat capture date as POISXct; retain PIT#, species, and capture date
pit_capture <-read.csv("test_2019_01_21.csv", stringsAsFactors = FALSE, colClasses = "character")
pit_capture<- select(pit_capture, c(Lake, PIT, Length, Sex))
pit_capture$PIT<-as.character(pit_capture$PIT)
head(pit_capture)
length(unique(pit_capture$PIT))

#Boat Ramp Site  

boatramp<-read.table("Boat_ramp_complete.log", header=FALSE, fill=TRUE,col.names=c("D", "Date", "Time", "Time2", "HA", "PIT", "Antenna", "Col1","Col2"), na.strings=c("", "NA"))
boatramp<-select(boatramp, c(Date, Time, PIT, Antenna))

boatramp$DATETIME<- as.POSIXct(paste(boatramp$Date,boatramp$Time), format='%Y-%m-%d %H:%M:%S', tz="CDT") #Reformat as POSIXct
boatramp<-boatramp[-which(is.na(boatramp$DATETIME)),] #remove NA values
boatramp$PIT<-as.character(boatramp$PIT) #toString(boatramp$PIT)
boatramp$PIT<-str_sub(boatramp$PIT, 11, 16)
boatramp$PIT[boatramp$PIT==""] <- NA
boatramp<-boatramp[-which(is.na(boatramp$PIT)),]
boatramp<-boatramp[-which(boatramp$PIT=="390146"),] #This PIT ID has a 2018 read (prior to data collection start)
boatramp$Site<-"B"
# write.csv( boatramp, "cleaned_boatramp.csv")

merged_br<- merge(boatramp, pit_capture,  by="PIT")
# merged_br<-boatramp
head(merged_br)

length(unique(merged_br$PIT))
```

### Overview of unique visits per day
```{r}
ggplot(data=merged_br, aes(DATETIME, as.factor(PIT), color=Antenna)) +
  geom_point(alpha=0.5) # +
  # # scale_x_datetime(date_breaks="1 day")+
  # xlab("Date")+
  # ylab("Carp PIT ID")+
  # theme(axis.text.x=element_text(angle=90), axis.text=element_text(size=8), axis.title = element_text(size=10))

dates<-unique(merged_br$DATETIME) #how many dates of observation in dataset?
(min_date<-min(dates))
(max_date<-max(dates))

start_date<-as.POSIXct("2019-07-23 12:00:00 CDT")
end_date<-as.POSIXct("2019-10-29 12:00:00 CDT")

num_days<-as.numeric(end_date-start_date)
sampling_df <-data.frame(day=1:num_days, uniqueID=rep(NA, num_days))
degree_list<-NULL

for(i in 1:num_days){
  sub_combined<-merged_br %>% filter(DATETIME >= as.POSIXct(start_date+ (i-1)*86400, tz="CDT") & DATETIME <= as.POSIXct(start_date + i*86400, tz="CDT")) #86400 seconds/24 hours
  # print(sub_combined)
  sampling_df$uniqueID[i]<-length(unique(sub_combined$PIT))
  PITs<-unique(sub_combined$PIT)
  if(length(PITs)>0){
  carp.degree<-data.frame(PITs, numsites= rep(NA, length(PITs)))
      for(j in 1:length(PITs)){
        carp.degree$numsites[j]<-length(unique(sub_combined$Antenna[which(sub_combined$PIT==PITs[j])]))
      }
  degree_list[[i]]<-carp.degree
  }
}


sampling_df$uniqueID<-as.numeric(sampling_df$uniqueID)
barplot(uniqueID ~day, data=sampling_df, xlab="Sampling Day", ylab="Number of unique carp")

dt<-rbindlist(degree_list, use.names=TRUE, fill=TRUE, idcol="SamplingDay")

p<- ggplot(dt, aes(x=numsites)) + geom_histogram(center=0)
p + transition_time(SamplingDay) +
  labs(title = "Boat Ramp-Sampling Day: {frame_time}")

#Are carp visiting all antennae at BR site (across total sampling period)?
PITs<-unique(merged_br$PIT)
carp.degree<-data.frame(PITs, numsites= rep(NA, length(PITs)))
for(i in 1:length(PITs)){
  carp.degree$numsites[i]<-length(unique(merged_br$Antenna[which(merged_br$PIT==PITs[i])]))
}

hist(carp.degree$numsites, xlab= "Number of unique antennae visited per carp", main=NULL, cex.lab=1.5, cex.axis=1.5, breaks=seq(min(carp.degree$numsites)-0.5, max(carp.degree$numsites)+0.5, by=1), right=TRUE)

#Bipartite network for boat ramp site
edgelist<-data.frame(PIT=merged_br$PIT, Reader=merged_br$Antenna)

A <- spMatrix(nrow=length(unique(edgelist$PIT)),
        ncol=length(unique(edgelist$Reader)),
        i = as.numeric(factor(edgelist$PIT)),
        j = as.numeric(factor(edgelist$Reader)),
        x = rep(1, length(as.numeric(edgelist$PIT))) )
row.names(A) <- levels(factor(edgelist$PIT))
colnames(A) <- levels(factor(edgelist$Reader))



#using carp data
bi<-graph.incidence(A, mode="all") #undirected, named graph that is bipartite
pr<-bipartite.projection(bi) 
#co-membership network of nodes ($proj1), or a network of groups that share members ($proj2)

# get.adjacency(pr$proj1,sparse=FALSE,attr="weight")
plot(pr$proj2)

visweb(t(A), circles=TRUE,  boxes=FALSE,  labsize=1, circle.max=1.5, text="no", plotsize= 18)
plotweb(as.matrix(A), text.rot=90, labsize=1, low.lablength = 6, text.low.col="black")
```
```{r}
num_days<-as.numeric(end_date-start_date)
network_df <-data.frame(day=1:num_days, nnodes=rep(NA,num_days), mean_degree=rep(NA, num_days), transitivity=rep(NA, num_days), edge_density=rep(NA, num_days), diameter=rep(NA, num_days), centralization=rep(NA, num_days), eigen= rep(NA, num_days), btwn= rep(NA, num_days),modularity=rep(NA, num_days))
degree_list<-NULL

for(i in 1:num_days){
  sub_combined<-merged_br %>% filter(DATETIME >= as.POSIXct(start_date+ (i-1)*86400, tz="CDT") & DATETIME <= as.POSIXct(start_date + i*86400, tz="CDT")) #86400 seconds/24 hours
  # print(sub_combined)
  
  edgelist<-data.frame(PIT=sub_combined$PIT, Reader=sub_combined$Antenna)
  network_df$nnodes[i]<-length(unique(sub_combined$PIT))
  
if(nrow(edgelist)>0){
  A <- spMatrix(nrow=length(unique(edgelist$PIT)),
          ncol=length(unique(edgelist$Reader)),
          i = as.numeric(factor(edgelist$PIT)),
          j = as.numeric(factor(edgelist$Reader)),
          x = rep(1, length(as.numeric(edgelist$PIT))) )
  row.names(A) <- levels(factor(edgelist$PIT))
  colnames(A) <- levels(factor(edgelist$Reader))
  
  bi<-graph.incidence(A, mode="all") #undirected, named graph that is bipartite
  pr<-bipartite.projection(bi) 
  #co-membership network of nodes ($proj1), or a network of groups that share members ($proj2)
  plot(pr$proj1, main=paste("Day =", i))
  
  network_df$mean_degree[i]<-mean(degree_distribution(pr$proj1))
  network_df$transitivity[i]<-transitivity(pr$proj1, "global")
  network_df$edge_density[i]<-edge_density(pr$proj1, loops=F)
  network_df$diameter[i]<-diameter(pr$proj1, directed=F, weights=NA)
  network_df$centralization[i]<-centr_degree(pr$proj1, loops=FALSE, normalized=T)$centralization
  network_df$eigen[i]<-centr_eigen(pr$proj1, directed=F, normalized=T)$centralization 
  network_df$btwn[i]<-centr_betw(pr$proj1, directed=F, normalized=T)$centralization
  network_df$modularity[i]<-modularity(pr$proj1, membership(cluster_walktrap(pr$proj1)))
  }
}

head(network_df)
```

Look at changes in network topology through time
```{r}
plot(network_df$day, network_df$nnodes, type="l", xlab= "Sampling day", ylab="Number of nodes in daily network")
points(network_df$day, network_df$nnodes, col="red")

plot(network_df$day, network_df$edge_density, type="l", xlab= "Sampling day", ylab="Edge density")
points(network_df$day, network_df$edge_density, col="blue")

plot(network_df$day, network_df$transitivity, type="l", xlab= "Sampling day", ylab="Global transitivity")
points(network_df$day, network_df$transitivity, col="blue")

plot(network_df$day, network_df$diameter, type="l", xlab= "Sampling day", ylab="Network diameter")
points(network_df$day, network_df$diameter, col="blue")

plot(network_df$day, network_df$centralization, type="l", xlab= "Sampling day", ylab="Normalized centralization")
points(network_df$day, network_df$centralization, col="blue")


plot(network_df$day, network_df$modularity, type="l", xlab= "Sampling day", ylab="Modularity")
points(network_df$day, network_df$modularity, col="blue")


plot(network_df$day, network_df$eigen, type="l", xlab= "Sampling day", ylab="Eigenvalue centralization")
points(network_df$day, network_df$eigen, col="blue")


plot(network_df$day, network_df$btwn, type="l", xlab= "Sampling day", ylab="Betweenness centralization")
points(network_df$day, network_df$btwn, col="blue")




```

